name: YOLO
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8.20
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=11.8
  - pip
  - pip:
      - -r requirements.txt

